# Generated by Django 5.1.4 on 2024-12-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aprendiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nota1', models.FloatField()),
                ('nota2', models.FloatField()),
                ('nota3', models.FloatField()),
                ('nota4', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='calificacion',
            old_name='estudiante',
            new_name='aprendiz',
        ),
    ]
